version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes: [.:/app]
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
